filebeat.inputs:
  - type: log
    id: api-log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/api.log
    fields:
      index_name: "api-log" # 인덱스명
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

  - type: log
    id: api-error-log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/api-error.log
    fields:
      index_name: "api-error-log" # 인덱스명
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["host.docker.internal:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
