version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./mongodb/data/db:/data/db
    networks:
      - dev-network
    hostname: mongodb

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    container_name: mongo-express
    ports:
      - "27117:8081"
    environment:
      - PORT=8081
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
      - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongodb:27017/
    networks:
      - dev-network
    hostname: mongo-express

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - dev-network
    hostname: jenkins

networks:
  dev-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
