server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/security

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, busrefresh
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    busrefresh:
      enabled: true