server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create-drop
    show-sql: true
    open-in-view: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, refresh, health, beans
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    refresh:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true
