spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${local-db.postgres.host}:${local-db.postgres.port}/${local-db.postgres.name}
    username: ${local-db.postgres.username}
    password: ${local-db.postgres.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

  data:
    mongodb:
      host: ${local-db.mongodb.host}
      port: ${local-db.mongodb.port}
      authentication-database: ${local-db.mongodb.authentication-database}
      database: ${local-db.mongodb.database}
      username: ${local-db.mongodb.username}
      password: ${local-db.mongodb.password}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.transaction.interceptor: trace
