server:
  port: 8080

spring:
  application:
    name : Spring-Batch-Jenkins_Study

  config:
    import:
      - security/application-db.yml

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
