server:
  port: 8080

spring:
  config:
    import:
      - security/application-db.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${local-db.host}:${local-db.port}/${local-db.name}
    username: ${local-db.username}
    password: ${local-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    open-in-view: true
    show-sql: true

  batch:    # DefaultBatchConfiguration 사용하면 적용 안됨.
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: Job2

